#.github/sync-Python-Actions.GoodInfo.Analyzer.yml
group:
  - files:
      # No. 51: FactSet detailed report
      - source: data/reports/factset_detailed_report_latest.csv
        dest:   data/stage1_raw/factset_detailed_report_latest.csv
    repos: |
        wenchiehlee-investment/Python-Actions.GoodInfo.Analyzer
