# .github/sync-to-YahooFinance.yml
group:
  - files:
      - source: data/reports/raw_factset_detailed_report.csv
        dest:   data/reports/raw_factset_detailed_report.csv
      - source: raw_column_definition.md
        dest:   definitions/raw_column_definition_Factset.md
    repos: |
      wenchiehlee/Yahoo.Finance
