name: Sync to Analyzer

on:
  workflow_dispatch:
  schedule:
    - cron: "0 19 * * *"  # Runs every day at 7:00 PM UTC (3:00 AM Taipei time)
  push:
     branches:
       - main
     paths:
       - data/reports/raw_factset_detailed_report.csv
       - raw_column_definition.md
       - .github/sync-to-YahooFinance.yml
       - .github/workflows/sync-to-Analyzer.yml

concurrency:
  group: sync-analyzer
  cancel-in-progress: false

jobs:
  sync-backup-workflow:
    runs-on: ubuntu-latest
    # if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v4

      - name: Sync up to Analyzer
        uses: BetaHuhn/repo-file-sync-action@latest
        with:
          GH_PAT: ${{ secrets.REPO_FILE_SYNC_WENCHIEHLEE_INVESTMENT }}
          CONFIG_PATH: .github/sync-to-Analyzer.yml
          COMMIT_EACH_FILE: false
          PR_LABELS: "automated-sync"
          SKIP_PR: true

      - name: Sync up to TAIEX.TW
        uses: BetaHuhn/repo-file-sync-action@latest
        with:
          GH_PAT: ${{ secrets.REPO_FILE_SYNC_WENCHIEHLEE_MONEY }}
          CONFIG_PATH: .github/sync-to-TAIEX.yml
          COMMIT_EACH_FILE: false
          PR_LABELS: "automated-sync"
          SKIP_PR: true

      - name: Sync up to Yahoo.Finance
        uses: BetaHuhn/repo-file-sync-action@latest
        with:
          GH_PAT: ${{ secrets.REPO_FILE_SYNC_WENCHIEHLEE }}
          CONFIG_PATH: .github/sync-to-YahooFinance.yml
          COMMIT_EACH_FILE: false
          PR_LABELS: "automated-sync"
          SKIP_PR: true
